#ifndef ERRORCODE_H
#define ERRORCODE_H

#define		ERROR_NONE							0

#define		ERROR_CASS_INPATH					1
#define		ERROR_CASS_OUTPATH					2
#define		ERROR_CASS_STARTRANGE				3
#define		ERROR_CASS_ENDRANGE					4
#define		ERROR_CASS_RANGE					5
#define		ERROR_RECIPE_SELECT					6
#define		ERROR_USECASS_SELECT				7
#define		ERROR_JOB_RUN_ALREADY				8
			/*
			ERROR_JOB_RUN_ALREADY													FA	POPUP

			<START EVENT>		TRANSFER SYSTEM 이 Running 중일때					O	X			"TRANSFER SYSTEM IS RUNNING ALREADY"
			<START EVENT>		MANUAL START 시 해당 SIDE가 Running 중일때			O	X			"AUTO SYSTEM IS RUNNING ALREADY"
			<START EVENT>		AUTO START 시 해당 SIDE가 Running 중이고			O	X			"AUTO SYSTEM IS RUNNING ALREADY"
								FA_SINGLE_CASS_MULTI_RUN 이 FALSE일때
			<START EVENT>		MTLOUT을 사용하지 않을때 회수 SIDE가 Running중일때	O	X			"AUTO SYSTEM IS RUNNING ALREADY 2"
			<START EVENT>		REGIST 정보사 Disable일때							O	X			"AUTO SYSTEM CAN NOT RUNNING"
			<START EVENT>		JOB으로 START한 내용이 Running중일때				O	O			""
								Process Job 공간이 없을때
								Control Job 이 있을때

			START				MTLOUT을 사용하지 않을때							X	O	
								CTC.MAIN_CONTROL? IO가 IDLE이 아닐때
			START				LOAD/UNLOAD Part가 Running 중일때					X	O	

			RECIPE CHECKING		EVENT로 START 시									O	O
								JOB으로 START한 내용이 Running중일때
								Process Job 공간이 없을때
								Control Job 이 있을때
			*/
#define		ERROR_JOB_PARAM_ERROR				9

#define		ERROR_NOT_SINGLE_CHAMBER			10
#define		ERROR_LOT_RECIPE_DATA				11
#define		ERROR_CLST_RECIPE_DATA				12
#define		ERROR_RECIPE_HAS_NO_WAFER			13
#define		ERROR_TARGET_CHAMBER_ERROR			14
#define		ERROR_DISABLE_USE					15
#define		ERROR_ROBOT_HAS_WAFER				16
#define		ERROR_CHAMBER_HAS_WAFER				17
#define		ERROR_PM_RECIPE_FILE_ERROR			18
#define		ERROR_PM_SIDE_ERROR					19
#define		ERROR_CHAMBER_HAS_NOT_WAFER			20

#define		ERROR_CASS_MAP						21
#define		ERROR_CASS_MAP2						22
#define		ERROR_READY_FAILURE					23
#define		ERROR_END_FAILURE					24
#define		ERROR_HANDOFF_IN_FAILURE			25
#define		ERROR_HANDOFF_OUT_FAILURE			26
#define		ERROR_DISABLE_NOT_GO_MODULE			27
#define		ERROR_ABORT_BUT_REMAIN_PROCESS		28
#define		ERROR_WAFER_DISAPPEAR				29
#define		ERROR_VERIFY_FAIL					30	// 2011.08.01

#define		ERROR_SLOTFIX_FAIL1					31	// 2015.10.12
#define		ERROR_SLOTFIX_FAIL2					32	// 2015.10.12

#define		ERROR_DEADLOCK_HAPPEN				41	// 2018.09.04

#define		ERROR_TRANSFER_STOP_BY_ABORT		161
#define		ERROR_TRANSFER_STOP_BY_ERROR		162
#define		ERROR_SDM_PART_RUNNING				163

#define		ERROR_BMPROCESS_STOP_BY_ABORT		171
#define		ERROR_BMPROCESS_STOP_BY_ERROR		172
#define		ERROR_BMPROCESS_INVALID_CHAMBER		173
#define		ERROR_BMPROCESS_INVALID_RANGE		174
#define		ERROR_BMPROCESS_INVALID_ROBOT		175
#define		ERROR_BMPROCESS_INVALID_WAFER		176
#define		ERROR_BMPROCESS_NO_WAFER			177
#define		ERROR_BMPROCESS_NO_TAGET_CHAMBER	178

#define		ERROR_FILE_SYSTEM_CFG				201
#define		ERROR_FILE_SCHEDULE_CFG				202
#define		ERROR_FILE_FILE_CFG					203
#define		ERROR_FILE_ROBOT_CFG				204
#define		ERROR_FILE_ROBOT2_CFG				205

#define		ERROR_BY_USER						501
#define		ERROR_NOT_PREPARE					502

#define		ERROR_CASS_DIFFSLOT_SELECT			701
#define		ERROR_CASS_OVERRANGESLOT_SELECT		702
#define		ERROR_CASS_SLOTDUPLICATE_SELECT		703
#define		ERROR_CASS_OVER2CASS_SELECT			704

#define		ERROR_SYSTEM_ABORTED2				996 // 2008.03.13
//
#define		ERROR_THREAD_FAIL					997
#define		ERROR_SYSTEM_ERROR					998
#define		ERROR_SYSTEM_ABORTED				999

#endif
