#ifndef SCH_A0_F_H
#define SCH_A0_F_H



int USER_DLL_SCH_INF_ENTER_CONTROL_FEM_DEFAULT_STYLE_0( int CHECKING_SIDE , int mode );
int USER_DLL_SCH_INF_RUN_CONTROL_FEM_DEFAULT_STYLE_0( int CHECKING_SIDE );

int USER_DLL_SCH_INF_ENTER_CONTROL_FEM_SWITCH_STYLE_0( int CHECKING_SIDE , int mode );
int USER_DLL_SCH_INF_RUN_CONTROL_FEM_SWITCH_STYLE_0( int CHECKING_SIDE );

int USER_DLL_SCH_INF_ENTER_CONTROL_FEM_DOUBLE_STYLE_0( int CHECKING_SIDE , int mode );
int USER_DLL_SCH_INF_RUN_CONTROL_FEM_DOUBLE_STYLE_0( int CHECKING_SIDE );



#endif

